export const ENV = {
  NATIVE_DEBUG: 'NATIVE_DEBUG',
  IPC_PATH_KEY: '_ALICE_IPC_PATH',
  CODE_PATH_KEY: '_ALICE_CODE_PATH',
  WORKER_CREDENTIAL_KEY: '_ALICE_WORKER_CREDENTIAL',
  FUNC_HANDLER_KEY: '_ALICE_FUNC_HANDLER',
  FUNC_INITIALIZER_KEY: '_ALICE_FUNC_INITIALIZER',
  LOG_LEVEL: '_ALICE_LOG_LEVEL',
};
