export const ENV = {
  NATIVE_DEBUG: 'NATIVE_DEBUG',
  IPC_PATH_KEY: '_NOSLATED_IPC_PATH',
  CODE_PATH_KEY: '_NOSLATED_CODE_PATH',
  WORKER_CREDENTIAL_KEY: '_NOSLATED_WORKER_CREDENTIAL',
  FUNC_HANDLER_KEY: '_NOSLATED_FUNC_HANDLER',
  FUNC_INITIALIZER_KEY: '_NOSLATED_FUNC_INITIALIZER',
  LOG_LEVEL: '_NOSLATED_LOG_LEVEL',
};
